name: Jekyll Video
description: Template for a video blog.
url: 'https://cecepmulya.github.io'
baseurl: '/video'
email: mulyadicecep@gmail.com
twitter: https://twitter.com/cecepsan
youtube: https://www.youtube.com/c2psan
facebook: https://www.facebook.com/utaja
google_analytics: 'UA-00000000-1'

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
